language: python

script:
  - tox

install:
  - pip install tox

matrix:
  include:
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.4"
      env: TOXENV=py34
    - python: "3.5"
      env: TOXENV=py35

    # Pypy
    - python: "pypy"
      env: TOXENV=py27

    # Linting
    - python: "3.5"
      env: TOXENV=lint

notifications:
  email: false
  irc: "irc.freenode.org#xelnext"
